# Generated by Django 3.0.7 on 2020-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
