# Generated by Django 3.0.7 on 2020-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200615_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
