# Generated by Django 3.0.7 on 2020-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200615_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
